/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using Nullables;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
using Vns.Erp.Core.Dao.NHibernate;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Admin.Dao;
using Vns.Erp.Core.Dao;
using Spring.Transaction.Interceptor;
using NHibernate.Transform;
using NHibernate.Criterion;
namespace Vns.Erp.Core.Admin.Dao.NHibernate
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>
	[Serializable]
	public sealed class DmKhangDao:GenericDao<DmKhang,Guid>,IDmKhangDao
	{
        #region IDao
        DmKhang IDao<DmKhang, Guid>.Merge(DmKhang entity)
        {
            if (VnsCheck.IsNullGuid(entity.Id)) entity.Id = Guid.NewGuid();
            HibernateTemplate.Merge(entity);

            return entity;
        }

        DmKhang IDao<DmKhang, Guid>.Save(DmKhang entity)
        {
            if (VnsCheck.IsNullGuid(entity.Id)) entity.Id = Guid.NewGuid();
            HibernateTemplate.Save(entity);

            return entity;
        }

        DmKhang IDao<DmKhang, Guid>.SaveOrUpdate(DmKhang entity)
        {
            if (VnsCheck.IsNullGuid(entity.Id)) entity.Id = Guid.NewGuid();
            HibernateTemplate.SaveOrUpdate(entity);

            return entity;
        }
        #endregion

        public IList<DmKhang> GetAllByDonviID(Guid DonviId)
        {
            ArrayList props = new ArrayList();
            ArrayList values = new ArrayList();
            props.Add("DonviId");
            values.Add(DonviId);
            return List(-1, -1, props, values, null);
        }
        public int GetNumberKhachHangByKyHieu(string KyHieu, Guid DonviId)
        {
            string sql = "select count(*) from DmKhang a where a.KyHieu like (:KyHieu) and DonviId = :DonviId";
            IQuery q = NHibernateSession.CreateQuery(sql);
            q.SetParameter("KyHieu", KyHieu);
            q.SetParameter("DonviId", DonviId);
            return q.UniqueResult<int>();
        }
        
        //public IList<DmKhang> GetKhByNgaySinh(int p_thang)
        //{
        //    string sql = "select "+
        //                 "from DmKhang kh " +
        //                 "where MONTH(kh.NgaySinh) =:p_thang";
        //    IQuery q = NHibernateSession.CreateQuery(sql);
        //    q.SetParameter("p_thang", p_thang);
        //    return q.List<DmKhang>();
        //}

        public IList<DmKhang> GetKhByNgaySinh(int p_thang)
        {
            ICriteria isearch = NHibernateSession.CreateCriteria<DmKhang>();

            isearch.Add(Restrictions.Eq("Month(NgaySinh)", p_thang));
            
            isearch.AddOrder(new Order("NgaySinh", true));

            return isearch.List<DmKhang>();
        }
	}
}
