/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
namespace Vns.Erp.Core.Admin.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
	/// </summary>

	
	[Serializable]
	[DataContract(Namespace ="http://Vns.Erp.Core.Admin",IsReference=true)]
	public partial class AppHGroupForm : DomainObject<Guid>, INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }		
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		//private decimal _id; 
		private Guid _group_id;
        private Guid _form_id; 
		private decimal _form_order; 
		private string _image_index; 
		private string _note1; 
		private string _note2; 
		private string _note3; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public AppHGroupForm()
		{
				_group_id = Guid.Empty ; 
				_form_id = Guid.Empty ; 
				_form_order = 0; 
				_image_index =  String.Empty; 
				_note1 =  String.Empty; 
				_note2 =  String.Empty; 
				_note3 =  String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		
        //[DataMember]
        //public  decimal Id
        //{
        //    get { return _id; }
        //    set { _isChanged |= (_id != value); _id = value; }
        //    }
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
        public Guid GroupId
		{
			get { return _group_id; }
			set { _isChanged |= (_group_id != value); _group_id = value; }
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
        public Guid FormId
		{
			get { return _form_id; }
			set { _isChanged |= (_form_id != value); _form_id = value; }
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  decimal FormOrder
		{
			get { return _form_order; }
			set { _isChanged |= (_form_order != value); _form_order = value; }
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  string ImageIndex
		{
			get { return _image_index; }
			set	
			{
				if ( value != null)
					if( value.Length > 500)
						throw new ArgumentOutOfRangeException("Invalid value for ImageIndex", value, value.ToString());
				
				_isChanged |= (_image_index != value); _image_index = value;
			}
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  string Note1
		{
			get { return _note1; }
			set	
			{
				if ( value != null)
					if( value.Length > 500)
						throw new ArgumentOutOfRangeException("Invalid value for Note1", value, value.ToString());
				
				_isChanged |= (_note1 != value); _note1 = value;
			}
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  string Note2
		{
			get { return _note2; }
			set	
			{
				if ( value != null)
					if( value.Length > 500)
						throw new ArgumentOutOfRangeException("Invalid value for Note2", value, value.ToString());
				
				_isChanged |= (_note2 != value); _note2 = value;
			}
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  string Note3
		{
			get { return _note3; }
			set	
			{
				if ( value != null)
					if( value.Length > 500)
						throw new ArgumentOutOfRangeException("Invalid value for Note3", value, value.ToString());
				
				_isChanged |= (_note3 != value); _note3 = value;
			}
			}
			
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		
		#endregion
		
		
		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			AppHGroupForm castObj = (AppHGroupForm)obj; 
			return ( castObj != null ) &&
				( this.Id == castObj.Id);
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			
			int hash = 57; 
			hash = 27 * hash * Id.GetHashCode();
			return hash; 
		}
		#endregion
		
	}
}
