/*
insert license info here
*/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Domain;
using System.Collections.Generic;
namespace Vns.Erp.Core.Admin.Dao
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	public interface IDmNhomvattu1Dao:IDao<DmNhomvattu1,Guid>
	{
        IList<DmNhomvattu1> GetObjectAllByDonviID(Guid DonViId);
        IList<DmNhomvattu1> GetByMaNhomVT(string MaNhom, Guid DonViId);
        IList<DmNhomvattu1> GetAllByNhom(Guid DonViId, Decimal LoaiNhom);
	}
}
