Public Class ConstantMsgs

    Public Shared MSG_UPDATE_SUCCESSFULL As String = "Updated {0} Successfully!"
    Public Shared MSG_UPDATE_FAIL As String = "Update {0} Fail!"
    Public Shared MSG_INSERT_SUCCESSFULL As String = "Add {0} Successfully!"
    Public Shared MSG_INSERT_FAIL As String = "Add {0} Fail!"
    Public Shared MSG_DELETE_SUCCESSFULL As String = "Deleted {0} Successfully!"
    Public Shared MSG_DELETE_FAIL As String = "Delete {0} Fail!"
    Public Shared MSG_CONFIRM_UPDATE_CONTAINER_INVOICE As String = "Are you sure to Update Container Invoice Status?"
    Public Shared MSG_SELECT_A_RECORD As String = "Please select a record for delete"
    Public Shared MSG_SELECT_A_RECORD_FOR_DELETE As String = "Please select a record for delete"
    Public Shared MSG_SELECT_A_RECORD_FOR_COPY As String = "Please select a record for copy"
    'Public Shared MSG_CONFIRM_FOR_DELETE As String = "Are you sure to delete this record ?"
    Public Shared MSG_CONFIRM_FOR_DELETE As String = "Bạn chắc chắn muốn xóa bản ghi này ?"
    Public Shared MSG_ALERT_FOR_RECENT_DELETE As String = "Chứng từ bạn chọn vừa bị xóa bởi người dùng khác!"
    Public Shared MSG_OPEN_FILE As String = "Do you want open file {0} ?"
    Public Shared MSG_SELECT_CHECKED As String = "Please select a checked for {0}"
    Public Shared MSG_GRIDVIEW_IS_NOTHING As String = "Please select a row data Container List"
    Public Shared MSG_CHECKCODE_EXISTS_OR_UPDATE As String = "This code is already exists, are you sure update data?"
    Public Shared MSG_CHECKCODE_EXISTS As String = "This code {0} is already exists!"
    Public Shared MSG_REQUIRE_INPUT_TEXT As String = "Please input text box "
    Public Shared MSG_SAVE_DATA As String = "Data has changed, you want to save before exit?"
    Public Shared MSG_ALLOCATE As String = "Do not have {0} for container"
    Public Shared MSG_PROCESS_ALLOCATE As String = "Allocate THC is processing..."
    Public Shared MSG_UPDATE_THC_SUCCESS As String = "Updated THC Successfully"
    Public Shared MSG_IMPORT_SUCCESSFUL As String = "Imported {0} Successfully"
    Public Shared MSG_DATA_NOT_FOUND As String = "Data not found in excel file"
    Public Shared MSG_EXCEL_IS_INCORRECT As String = "Excel file is incorrect"
    Public Shared MSG_REQUIRE_ALLOCATE_FI As String = "FI not allocate or has paid tax"
    Public Shared MSG_ALLOCATED_THC As String = "THC has is Allocated"
    Public Shared MSG_HAVE_CUSTOMS_DECLARE As String = "Have customs declaration"
    Public Shared MSG_CONFIRM_UPDATE_A_RECORD As String = "Are you sure to update {0} ?"
    Public Shared MSG_CONFIRM_SELECT_A_RECORD_FOR_UPDATE As String = "Please select a record for update."
    Public Shared MSG_CONFIRM_FOB_PART_PRICE As String = "Fob Master is not equal to fob invoice. Please update!"
    Public Shared MSG_CONFIRM_ALLOCATE_A_RECORD As String = "Are you sure to Allocate this invoice?"
    Public Shared MSG_CONFIRM_SELECT_A_RECORD_FOR_ALLOCATE As String = "Please select a record for allocate!"
    Public Shared MSG_CONFIRM_NO_INVOICEDETAIlS_FOR_ALLOCATE As String = "This invoice does not have a invoice details to allocate!"
    Public Shared MSG_ALLOCATE_SUCCESSFULL As String = "Allocate Successfull!"
    Public Shared MSG_CONFIRM_INPUT As String = "Please input {0}!"
    Public Shared MSG_CONFIRM_INPUT_INVALID_NUMBER As String = "Please input format number for {0}!"

    Public Shared MSG_CONFIRM_UPDATE_SHIPMENT_ATA As String = "Are you sure to update those ATA?"
    Public Shared MSG_ALERT_CHOOSE_EDITATA As String = "Please choose EditATA?"
    Public Shared MSG_ALERT_SHIPMENT_ATA_INVALID As String = "ATA cannot less ETD! Please re-entry ATA"
    Public Shared MSG_ALERT_DO_NOT_EXIST As String = "Do not exist {0}"
    Public Shared MSG_ALERT_INVOICE_EXIST_PRE_CUSTOMS As String = "Invoice already existed Pre customs, Cannot move Invoice to other Bill."
    Public Shared MSG_ALERT_FIELD_IS_NOT_NULL As String = "{0} is not null"
    Public Shared MSG_ALERT_FIELD_TOO_LENGHT As String = "{0} too lenght"
    Public Shared MSG_ALERT_EXIST As String = "This is {0} exist! Please input other {0}"
    Public Shared MSG_CREATE_NEW As String = "This is {0}"
    Public Shared MSG_DEVANNING_STATUS As String = "6"
    Public Shared MSG_YARD_STATUS As String = "5"
    Public Shared MSG_GRIDVIEW_NOT_DATA As String = "Please select the record {0} to update or click to add a new record !"
    Public Shared MSG_COMPARE_ACTUAL_TAX_VAT As String = "Actual {0} # {1}"
    Public Shared MSG_CHANGE_DATA As String = "Data has changed, you do not want to save?"
    Public Shared MSG_ALERT_COMPARE_GREATER As String = "{0} can not greater than {0}."
    Public Shared MSG_ALERT_COMPARE_LOWER As String = "{0} can not lower than {1}."

    Public Shared STT_INVOICE_NEW As String = "NEW"
    Public Shared STT_INVOICE_ALLOCATING As String = "ALLOCATING"
    Public Shared STT_INVOICE_ALLOCATEDFI As String = "ALLOCATED FI"
    Public Shared STT_INVOICE_ALLOCATED As String = "ALLOCATED"
    Public Shared STT_INVOICE_BPRE As String = "BEING PRECUSTOMS"
    Public Shared STT_INVOICE_PRE As String = "PRECUSTOMS"
    Public Shared STT_INVOICE_BCUS As String = "BEING CUSTOMS"
    Public Shared STT_INVOICE_CUS As String = "CUSTOMS"
    Public Shared STT_INVOICE_CON As String = "CONFIRMED"
    Public Shared STT_INVOICE_PAID As String = "PAID"
    Public Shared STT_INVOICE_CODE_NEW As String = "0"
    Public Shared STT_INVOICE_CODE_ALLOCATING As String = "1"

    ' Message For Import Excel
    Public Shared MSG_EXCEL_IMPORT_SUCCESS As String = "Import data successfully"
    Public Shared MSG_EXCEL_NO_DATA As String = "Not found data in excel file"
    Public Shared MSG_EXCEL_INVAILD As String = "Invaild excel file"

    ' Message For Check Data Action
    Public Shared MSG_DELETED As String = "This record has been delete by another user."

#Region "MESSAGE"

    Public Shared MESSAGE_DELETE_CONFIRM As String = "Bạn chắc chắn muốn xóa dữ liệu đã chọn?"
    Public Shared MESSAGE_EDIT_SELECT_REQUIRE As String = "Bạn phải chọn dữ liệu để cập nhật."
    Public Shared MESSAGE_DELETE_SELECT_REQUIRE As String = "Bạn phải chọn dữ liệu để xóa."
    Public Shared MESSAGE_COPY_SELECT_REQUIRE As String = "You have to select row to copy."
    Public Shared MESSAGE_DUPLICATED_RECORD As String = "Record duplicated."
    Public Shared MESSAGE_SAVE_CONFIRM As String = "Do you want to save data?"
    Public Shared MESSAGE_NO_DATA_FOUND As String = "No data found"

    Public Shared MESSAGE_DELETE_SUCCESS As String = "Data deleted"
    Public Shared MESSAGE_SAVE_SUCCESS As String = "Data saved"
    Public Shared MESSAGE_EXPORT_OPEN_EXCEL_FILE_CONFIRM As String = "Exported successfully. Do you want to open the file?"

    
#End Region

    Public Shared msgKhoaSo As String = "Đã khóa sổ nên bạn không thể Thêm/Sửa/Xóa!"
    Public Shared msgTTChungTu As String = "Bạn chưa được Phân quyền cập nhật trạng thái Chứng từ!"

#Region "Conflicts"
    Public Shared MESSAGE_OVERWRITE_RECORD_CONFIRM As String = "Thông tin đã được cập nhật bởi người dùng khác!" & ControlChars.NewLine & "Bạn có muốn lưu đè thông tin ?"
    Public Shared MESSAGE_SAVE_DELETED_RECORD_WARNING As String = "Không thể lưu vì thông tin đã được xóa bởi người dùng khác !" & ControlChars.NewLine & "Hệ thống sẽ tự động đóng màn hình."
    Public Shared MESSAGE_SELECT_DELETED_RECORD_WARNING As String = "Thông tin đã được xóa bởi người dùng khác !" & ControlChars.NewLine & "Hệ thống sẽ tự động đóng màn hình."
#End Region
End Class
