/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
namespace Vns.Erp.Core.Accounting.Domain
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
    /// </summary>


    [Serializable]
    [DataContract(Namespace = "http://Vns.Erp.Core.Accounting.Domain", IsReference = true)]
    public partial class CtD : DomainObject<Guid>, INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
        #region Private Members
        private bool _isChanged;
        private bool _isDeleted;
        private Guid _ctd_id;
        private Guid _cth_id;
        private Guid _tk_no_id;
        private string _ma_tk_no;
        private string _ten_tk_no;
        private Guid _tk_co_id;
        private string _ma_tk_co;
        private string _ten_tk_co;
        private decimal _so_tien;
        private decimal _so_tien_nte;
        private string _noi_dung;
        private Guid _id_dm_hopdong_no;
        private string _ma_hopdong_no;
        private string _ky_hieu_hopdong_no;
        private string _ten_hopdong_no;
        private Guid _id_dm_hopdong_co;
        private string _ma_hopdong_co;
        private string _ky_hieu_hopdong_co;
        private string _ten_hopdong_co;
        private Guid _id_dm_ptqt_no;
        private Guid _id_dm_ptqt_co;
        private Guid _id_dm_phongban_no;
        private Guid _id_dm_phongban_co;
        private Guid _id_ct_ghiso;
        private string _ma_ct_ghiso_so;
        private string _ct_ghiso_trichyeu;
        private DateTime? _ct_ghiso_ngay;
        private decimal _da_ghiso;
        private Guid _id_dm_vuviec_no;
        private string _ma_vuviec_no;
        private string _ky_hieu_vuviec_no;
        private Guid _id_dm_vuviec_co;
        private string _ma_vuviec_co;
        private string _ky_hieu_vuviec_co;
        private Guid _id_dm_tudo_1_no;
        private Guid _id_dm_tudo_1_co;
        private Guid _id_dm_tudo_2_no;
        private Guid _id_dm_tudo_2_co;
        private Guid _id_dm_tudo_3_no;
        private Guid _id_dm_tudo_3_co;
        private Guid _id_dm_tudo_4_no;
        private Guid _id_dm_tudo_4_co;
        private Guid _id_dm_tudo_5_no;
        private Guid _id_dm_tudo_5_co;
        private decimal _loai_nghiep_vu;
        private Guid _id_khang_no;
        private string _ma_khang_no;
        private Guid _id_khang_co;
        private string _ma_khang_co;
        private Guid _id_doituong_1;
        private string _ma_doituong_1;
        private string _ten_doituong_1;
        private Guid _id_doituong_2;
        private string _ma_doituong_2;
        private string _ten_doituong_2;
        private Guid _id_doituong_3;
        private string _ma_doituong_3;
        private string _ten_doituong_3;
        private Guid _id_dm_khoanphi_no;
        private Guid _id_dm_khoanphi_co;
        private decimal _ty_gia_chenhlech;
        private decimal _nhom;
        private decimal _so_du;
        private Guid _id_doituong_hoadon;
        private string _ma_hoadon;
        private string _ky_hieu_hoadon;
        private string _ma_ro;
        private string _ten_ro;
        private string _ky_hieu_khang_no;
        private string _ten_khang_no;
        private string _ky_hieu_khang_co;
        private string _ten_khang_co;
        private decimal _phan_he;
        private string _bx_1;
        private string _bx_2;
        private string _bx_3;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public CtD()
        {
            _ctd_id = new Guid();
            _cth_id = new Guid();
            _tk_no_id = new Guid();
            _ma_tk_no = String.Empty;
            _ten_tk_no = String.Empty;
            _tk_co_id = new Guid();
            _ma_tk_co = String.Empty;
            _ten_tk_co = String.Empty;
            _so_tien = 0;
            _so_tien_nte = 0;
            _noi_dung = String.Empty;
            _id_dm_hopdong_no = new Guid();
            _ma_hopdong_no = String.Empty;
            _ky_hieu_hopdong_no = String.Empty;
            _ten_hopdong_no = String.Empty;
            _id_dm_hopdong_co = new Guid();
            _ma_hopdong_co = String.Empty;
            _ky_hieu_hopdong_co = String.Empty;
            _ten_hopdong_co = String.Empty;
            _id_dm_ptqt_no = new Guid();
            _id_dm_ptqt_co = new Guid();
            _id_dm_phongban_no = new Guid();
            _id_dm_phongban_co = new Guid();
            _id_ct_ghiso = new Guid();
            _ma_ct_ghiso_so = String.Empty;
            _ct_ghiso_trichyeu = String.Empty;
            _ct_ghiso_ngay = DateTime.MaxValue;
            _da_ghiso = 0;
            _id_dm_vuviec_no = new Guid();
            _ma_vuviec_no = String.Empty;
            _ky_hieu_vuviec_no = String.Empty;
            _id_dm_vuviec_co = new Guid();
            _ma_vuviec_co = String.Empty;
            _ky_hieu_vuviec_co = String.Empty;
            _id_dm_tudo_1_no = new Guid();
            _id_dm_tudo_1_co = new Guid();
            _id_dm_tudo_2_no = new Guid();
            _id_dm_tudo_2_co = new Guid();
            _id_dm_tudo_3_no = new Guid();
            _id_dm_tudo_3_co = new Guid();
            _id_dm_tudo_4_no = new Guid();
            _id_dm_tudo_4_co = new Guid();
            _id_dm_tudo_5_no = new Guid();
            _id_dm_tudo_5_co = new Guid();
            _loai_nghiep_vu = 0;
            _id_khang_no = new Guid();
            _ma_khang_no = String.Empty;
            _id_khang_co = new Guid();
            _ma_khang_co = String.Empty;
            _id_doituong_1 = new Guid();
            _ma_doituong_1 = String.Empty;
            _ten_doituong_1 = String.Empty;
            _id_doituong_2 = new Guid();
            _ma_doituong_2 = String.Empty;
            _ten_doituong_2 = String.Empty;
            _id_doituong_3 = new Guid();
            _ma_doituong_3 = String.Empty;
            _ten_doituong_3 = String.Empty;
            _id_dm_khoanphi_no = new Guid();
            _id_dm_khoanphi_co = new Guid();
            _ty_gia_chenhlech = 0;
            _nhom = 0;
            _so_du = 0;
            _id_doituong_hoadon = new Guid();
            _ma_hoadon = String.Empty;
            _ky_hieu_hoadon = String.Empty;
            _ma_ro = String.Empty;
            _ten_ro = String.Empty;
            _ky_hieu_khang_no = String.Empty;
            _ten_khang_no = String.Empty;
            _ky_hieu_khang_co = String.Empty;
            _ten_khang_co = String.Empty;
            _phan_he = 0;
            _bx_1 = String.Empty;
            _bx_2 = String.Empty;
            _bx_3 = String.Empty;
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid CtdId
        {
            get { return _ctd_id; }
            set { _isChanged |= (_ctd_id != value); _ctd_id = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid CthId
        {
            get { return _cth_id; }
            set { _isChanged |= (_cth_id != value); _cth_id = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid TkNoId
        {
            get { return _tk_no_id; }
            set { _isChanged |= (_tk_no_id != value); _tk_no_id = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaTkNo
        {
            get { return _ma_tk_no; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaTkNo", value, value.ToString());

                _isChanged |= (_ma_tk_no != value); _ma_tk_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenTkNo
        {
            get { return _ten_tk_no; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenTkNo", value, value.ToString());

                _isChanged |= (_ten_tk_no != value); _ten_tk_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid TkCoId
        {
            get { return _tk_co_id; }
            set { _isChanged |= (_tk_co_id != value); _tk_co_id = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaTkCo
        {
            get { return _ma_tk_co; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaTkCo", value, value.ToString());

                _isChanged |= (_ma_tk_co != value); _ma_tk_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenTkCo
        {
            get { return _ten_tk_co; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenTkCo", value, value.ToString());

                _isChanged |= (_ten_tk_co != value); _ten_tk_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoTien
        {
            get { return _so_tien; }
            set { _isChanged |= (_so_tien != value); _so_tien = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoTienNte
        {
            get { return _so_tien_nte; }
            set { _isChanged |= (_so_tien_nte != value); _so_tien_nte = Decimal.Round(value, 2); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string NoiDung
        {
            get { return _noi_dung; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for NoiDung", value, value.ToString());

                _isChanged |= (_noi_dung != value); _noi_dung = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmHopdongNo
        {
            get { return _id_dm_hopdong_no; }
            set { _isChanged |= (_id_dm_hopdong_no != value); _id_dm_hopdong_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaHopdongNo
        {
            get { return _ma_hopdong_no; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaHopdongNo", value, value.ToString());

                _isChanged |= (_ma_hopdong_no != value); _ma_hopdong_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuHopdongNo
        {
            get { return _ky_hieu_hopdong_no; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuHopdongNo", value, value.ToString());

                _isChanged |= (_ky_hieu_hopdong_no != value); _ky_hieu_hopdong_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenHopdongNo
        {
            get { return _ten_hopdong_no; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenHopdongNo", value, value.ToString());

                _isChanged |= (_ten_hopdong_no != value); _ten_hopdong_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmHopdongCo
        {
            get { return _id_dm_hopdong_co; }
            set { _isChanged |= (_id_dm_hopdong_co != value); _id_dm_hopdong_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaHopdongCo
        {
            get { return _ma_hopdong_co; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaHopdongCo", value, value.ToString());

                _isChanged |= (_ma_hopdong_co != value); _ma_hopdong_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuHopdongCo
        {
            get { return _ky_hieu_hopdong_co; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuHopdongCo", value, value.ToString());

                _isChanged |= (_ky_hieu_hopdong_co != value); _ky_hieu_hopdong_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenHopdongCo
        {
            get { return _ten_hopdong_co; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenHopdongCo", value, value.ToString());

                _isChanged |= (_ten_hopdong_co != value); _ten_hopdong_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmPtqtNo
        {
            get { return _id_dm_ptqt_no; }
            set { _isChanged |= (_id_dm_ptqt_no != value); _id_dm_ptqt_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmPtqtCo
        {
            get { return _id_dm_ptqt_co; }
            set { _isChanged |= (_id_dm_ptqt_co != value); _id_dm_ptqt_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmPhongbanNo
        {
            get { return _id_dm_phongban_no; }
            set { _isChanged |= (_id_dm_phongban_no != value); _id_dm_phongban_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmPhongbanCo
        {
            get { return _id_dm_phongban_co; }
            set { _isChanged |= (_id_dm_phongban_co != value); _id_dm_phongban_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdCtGhiso
        {
            get { return _id_ct_ghiso; }
            set { _isChanged |= (_id_ct_ghiso != value); _id_ct_ghiso = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaCtGhisoSo
        {
            get { return _ma_ct_ghiso_so; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaCtGhisoSo", value, value.ToString());

                _isChanged |= (_ma_ct_ghiso_so != value); _ma_ct_ghiso_so = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string CtGhisoTrichyeu
        {
            get { return _ct_ghiso_trichyeu; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for CtGhisoTrichyeu", value, value.ToString());

                _isChanged |= (_ct_ghiso_trichyeu != value); _ct_ghiso_trichyeu = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public DateTime? CtGhisoNgay
        {
            get { return _ct_ghiso_ngay; }
            set { _isChanged |= (_ct_ghiso_ngay != value); _ct_ghiso_ngay = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal DaGhiso
        {
            get { return _da_ghiso; }
            set { _isChanged |= (_da_ghiso != value); _da_ghiso = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmVuviecNo
        {
            get { return _id_dm_vuviec_no; }
            set { _isChanged |= (_id_dm_vuviec_no != value); _id_dm_vuviec_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaVuviecNo
        {
            get { return _ma_vuviec_no; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaVuviecNo", value, value.ToString());

                _isChanged |= (_ma_vuviec_no != value); _ma_vuviec_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuVuviecNo
        {
            get { return _ky_hieu_vuviec_no; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuVuviecNo", value, value.ToString());

                _isChanged |= (_ky_hieu_vuviec_no != value); _ky_hieu_vuviec_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmVuviecCo
        {
            get { return _id_dm_vuviec_co; }
            set { _isChanged |= (_id_dm_vuviec_co != value); _id_dm_vuviec_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaVuviecCo
        {
            get { return _ma_vuviec_co; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaVuviecCo", value, value.ToString());

                _isChanged |= (_ma_vuviec_co != value); _ma_vuviec_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuVuviecCo
        {
            get { return _ky_hieu_vuviec_co; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuVuviecCo", value, value.ToString());

                _isChanged |= (_ky_hieu_vuviec_co != value); _ky_hieu_vuviec_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo1No
        {
            get { return _id_dm_tudo_1_no; }
            set { _isChanged |= (_id_dm_tudo_1_no != value); _id_dm_tudo_1_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo1Co
        {
            get { return _id_dm_tudo_1_co; }
            set { _isChanged |= (_id_dm_tudo_1_co != value); _id_dm_tudo_1_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo2No
        {
            get { return _id_dm_tudo_2_no; }
            set { _isChanged |= (_id_dm_tudo_2_no != value); _id_dm_tudo_2_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo2Co
        {
            get { return _id_dm_tudo_2_co; }
            set { _isChanged |= (_id_dm_tudo_2_co != value); _id_dm_tudo_2_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo3No
        {
            get { return _id_dm_tudo_3_no; }
            set { _isChanged |= (_id_dm_tudo_3_no != value); _id_dm_tudo_3_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo3Co
        {
            get { return _id_dm_tudo_3_co; }
            set { _isChanged |= (_id_dm_tudo_3_co != value); _id_dm_tudo_3_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo4No
        {
            get { return _id_dm_tudo_4_no; }
            set { _isChanged |= (_id_dm_tudo_4_no != value); _id_dm_tudo_4_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo4Co
        {
            get { return _id_dm_tudo_4_co; }
            set { _isChanged |= (_id_dm_tudo_4_co != value); _id_dm_tudo_4_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo5No
        {
            get { return _id_dm_tudo_5_no; }
            set { _isChanged |= (_id_dm_tudo_5_no != value); _id_dm_tudo_5_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo5Co
        {
            get { return _id_dm_tudo_5_co; }
            set { _isChanged |= (_id_dm_tudo_5_co != value); _id_dm_tudo_5_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal LoaiNghiepVu
        {
            get { return _loai_nghiep_vu; }
            set { _isChanged |= (_loai_nghiep_vu != value); _loai_nghiep_vu = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdKhangNo
        {
            get { return _id_khang_no; }
            set { _isChanged |= (_id_khang_no != value); _id_khang_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaKhangNo
        {
            get { return _ma_khang_no; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaKhangNo", value, value.ToString());

                _isChanged |= (_ma_khang_no != value); _ma_khang_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdKhangCo
        {
            get { return _id_khang_co; }
            set { _isChanged |= (_id_khang_co != value); _id_khang_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaKhangCo
        {
            get { return _ma_khang_co; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaKhangCo", value, value.ToString());

                _isChanged |= (_ma_khang_co != value); _ma_khang_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDoituong1
        {
            get { return _id_doituong_1; }
            set { _isChanged |= (_id_doituong_1 != value); _id_doituong_1 = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaDoituong1
        {
            get { return _ma_doituong_1; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for MaDoituong1", value, value.ToString());

                _isChanged |= (_ma_doituong_1 != value); _ma_doituong_1 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenDoituong1
        {
            get { return _ten_doituong_1; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenDoituong1", value, value.ToString());

                _isChanged |= (_ten_doituong_1 != value); _ten_doituong_1 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDoituong2
        {
            get { return _id_doituong_2; }
            set { _isChanged |= (_id_doituong_2 != value); _id_doituong_2 = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaDoituong2
        {
            get { return _ma_doituong_2; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for MaDoituong2", value, value.ToString());

                _isChanged |= (_ma_doituong_2 != value); _ma_doituong_2 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenDoituong2
        {
            get { return _ten_doituong_2; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenDoituong2", value, value.ToString());

                _isChanged |= (_ten_doituong_2 != value); _ten_doituong_2 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDoituong3
        {
            get { return _id_doituong_3; }
            set { _isChanged |= (_id_doituong_3 != value); _id_doituong_3 = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaDoituong3
        {
            get { return _ma_doituong_3; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for MaDoituong3", value, value.ToString());

                _isChanged |= (_ma_doituong_3 != value); _ma_doituong_3 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenDoituong3
        {
            get { return _ten_doituong_3; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenDoituong3", value, value.ToString());

                _isChanged |= (_ten_doituong_3 != value); _ten_doituong_3 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmKhoanphiNo
        {
            get { return _id_dm_khoanphi_no; }
            set { _isChanged |= (_id_dm_khoanphi_no != value); _id_dm_khoanphi_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmKhoanphiCo
        {
            get { return _id_dm_khoanphi_co; }
            set { _isChanged |= (_id_dm_khoanphi_co != value); _id_dm_khoanphi_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal TyGiaChenhlech
        {
            get { return _ty_gia_chenhlech; }
            set { _isChanged |= (_ty_gia_chenhlech != value); _ty_gia_chenhlech = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal Nhom
        {
            get { return _nhom; }
            set { _isChanged |= (_nhom != value); _nhom = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoDu
        {
            get { return _so_du; }
            set { _isChanged |= (_so_du != value); _so_du = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDoituongHoadon
        {
            get { return _id_doituong_hoadon; }
            set { _isChanged |= (_id_doituong_hoadon != value); _id_doituong_hoadon = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaHoadon
        {
            get { return _ma_hoadon; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for MaHoadon", value, value.ToString());

                _isChanged |= (_ma_hoadon != value); _ma_hoadon = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuHoadon
        {
            get { return _ky_hieu_hoadon; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuHoadon", value, value.ToString());

                _isChanged |= (_ky_hieu_hoadon != value); _ky_hieu_hoadon = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaRo
        {
            get { return _ma_ro; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaRo", value, value.ToString());

                _isChanged |= (_ma_ro != value); _ma_ro = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenRo
        {
            get { return _ten_ro; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenRo", value, value.ToString());

                _isChanged |= (_ten_ro != value); _ten_ro = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuKhangNo
        {
            get { return _ky_hieu_khang_no; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuKhangNo", value, value.ToString());

                _isChanged |= (_ky_hieu_khang_no != value); _ky_hieu_khang_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenKhangNo
        {
            get { return _ten_khang_no; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for TenKhangNo", value, value.ToString());

                _isChanged |= (_ten_khang_no != value); _ten_khang_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuKhangCo
        {
            get { return _ky_hieu_khang_co; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuKhangCo", value, value.ToString());

                _isChanged |= (_ky_hieu_khang_co != value); _ky_hieu_khang_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenKhangCo
        {
            get { return _ten_khang_co; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for TenKhangCo", value, value.ToString());

                _isChanged |= (_ten_khang_co != value); _ten_khang_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal PhanHe
        {
            get { return _phan_he; }
            set { _isChanged |= (_phan_he != value); _phan_he = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string Bx1
        {
            get { return _bx_1; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for Bx1", value, value.ToString());

                _isChanged |= (_bx_1 != value); _bx_1 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string Bx2
        {
            get { return _bx_2; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for Bx2", value, value.ToString());

                _isChanged |= (_bx_2 != value); _bx_2 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string Bx3
        {
            get { return _bx_3; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for Bx3", value, value.ToString());

                _isChanged |= (_bx_3 != value); _bx_3 = value;
            }
        }


        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return _isChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsDeleted
        {
            get { return _isDeleted; }
        }

        #endregion


        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public void MarkAsDeleted()
        {
            _isDeleted = true;
            _isChanged = true;
        }


        #endregion


        #region Equals And HashCode Overrides
        /// <summary>
        /// local implementation of Equals based on unique value members
        /// </summary>
        public override bool Equals(object obj)
        {
            if (this == obj) return true;
            if ((obj == null) || (obj.GetType() != this.GetType())) return false;
            CtD castObj = (CtD)obj;
            return (castObj != null) &&
                (this._ctd_id == castObj.CtdId);
        }

        /// <summary>
        /// local implementation of GetHashCode based on unique value members
        /// </summary>
        public override int GetHashCode()
        {

            int hash = 57;
            hash = 27 * hash * _ctd_id.GetHashCode();
            return hash;
        }
        #endregion

    }
}
