/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Admin.Dao;
using Vns.Erp.Core.Admin.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
using System.ServiceModel.Activation;
namespace Vns.Erp.Core.Admin.Service
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
	public class AppDvGroupService:GenericService<AppDvGroup,decimal>, IAppDvGroupService
	{
	    public IAppDvGroupDao AppDvGroupDao
        {
            get { return (IAppDvGroupDao)Dao; }
            set { Dao = value; }
        }

         public void DeleteByG(Guid groupid)
         {
             AppDvGroupDao.DeleteByG(groupid);
         }

         #region "BO Functions"

         public IList<AppDvGroup> GetByDV(Guid DONVI_ID)
         {         
            ArrayList props = new ArrayList();
            ArrayList values = new ArrayList();
            props.Add("DvId");
            values.Add(DONVI_ID);
            return AppDvGroupDao.List(-1, -1, props, values, null);
         }

         public IList<AppDvGroup> GetByGroup(Guid GROUP_ID)
         {
             ArrayList props = new ArrayList();
             ArrayList values = new ArrayList();
             props.Add("GroupId");
             values.Add(GROUP_ID);
             return AppDvGroupDao.List(-1, -1, props, values, null);
         }

         public void DeleteByDVGroup(string DV_ID, Guid GROUP_ID)
         {
             //APP_Dv_GroupDAO.Instance.DeleteByDVGroup(DV_ID, GROUP_ID);
         }

         #endregion

	}
}
