/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Admin.Dao;
using Vns.Erp.Core.Admin.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.ServiceModel.Activation;
using System.Collections.Generic;
namespace Vns.Erp.Core.Admin.Service
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
    public class DmDvtService : GenericService<DmDvt, Guid>, IDmDvtService
    {
        public IDmDvtDao DmDvtDao
        {
            get { return (IDmDvtDao)Dao; }
            set { Dao = value; }
        }

        public IList<DmDvt> GetAllByDonviID(Guid DonviId)
        {
            ArrayList props = new ArrayList();
            ArrayList values = new ArrayList();
            ArrayList expressions = new ArrayList();

            props.Add("DonviId");
            values.Add(DonviId);
            expressions.Add("=");

            return DmDvtDao.List(-1, -1, props, values);
        }
    }
}
