/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Admin.Dao;
using Vns.Erp.Core.Admin.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
using System.ServiceModel.Activation;
namespace Vns.Erp.Core.Admin.Service
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
	public class DmNguonTscdService:GenericService<DmNguonTscd,Guid>, IDmNguonTscdService
	{
	     public IDmNguonTscdDao DmNguonTscdDao
        {
            get { return (IDmNguonTscdDao)Dao; }
            set { Dao = value; }
        }
         public IList<DmNguonTscd> GetByMaNguon(string MaDmNguonTscd, Guid DonviId)
         {
             return DmNguonTscdDao.GetByMaNguon(MaDmNguonTscd, DonviId);
         }
         public IList<DmNguonTscd> GetAllByDonviID(Guid DonviId)
         {
             return DmNguonTscdDao.GetAllByDonviID(DonviId);
         }
	}
}
