/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Admin.Dao;
using Vns.Erp.Core.Admin.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
using System.ServiceModel.Activation;
namespace Vns.Erp.Core.Admin.Service
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
	public class DmNhomTscdService:GenericService<DmNhomTscd,Guid>, IDmNhomTscdService
	{
	     public IDmNhomTscdDao DmNhomTscdDao
        {
            get { return (IDmNhomTscdDao)Dao; }
            set { Dao = value; }
        }
         public IList<DmNhomTscd> GetAllByDonviID(Guid DonviId)
         {
             return DmNhomTscdDao.GetAllByDonviID(DonviId);
         }
         public IList<DmNhomTscd> GetMA_NHOM_TSCD(string MaNhom)
         {
             return DmNhomTscdDao.GetMA_NHOM_TSCD(MaNhom);
         }

         public IList<DmNhomTscd> GetbyLOAI_NHOM_TSCD(Guid DonviId, Decimal LoaiNhom)
         {
             ArrayList props = new ArrayList();
             ArrayList values = new ArrayList();
             props.Add("DonviId");
             values.Add(DonviId);
             props.Add("LoaiNhom");
             values.Add(LoaiNhom);
             return List(-1, -1, props, values, null);
         }
	}
}
