/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Admin.Dao;
using Vns.Erp.Core.Admin.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Activation;
namespace Vns.Erp.Core.Admin.Service
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
    public class LsTygiaService : GenericService<LsTygia, Guid>, ILsTygiaService
    {
        public ILsTygiaDao LsTygiaDao
        {
            get { return (ILsTygiaDao)Dao; }
            set { Dao = value; }
        }
        public IList<LsTygia> GetObjectByDoiTuong(string TenNgoaiteHt)
        {
            return LsTygiaDao.GetObjectByDoiTuong(TenNgoaiteHt);
        }

        public Decimal GetTyGiaNgoaiTe(Guid NgoaiteId, DateTime NgayTyGia)
        {
            LsTygia ls = LsTygiaDao.GetTyGiaNgoaiTe(NgoaiteId, NgayTyGia);
            if (ls == null)
            {
                return 0;
            }
            else
                return ls.SoTienQuydoi;
        }
        public IList<LsTygia> GetTyGiaByNgoaiTeId(Guid NgoaiteId)
        {
            return LsTygiaDao.GetTyGiaByNgoaiTeId(NgoaiteId);
        }
    }
}
