/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using Nullables;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
//using Erp.NHibernateConnectionFramework.Business.Helper;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Admin.Dao;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Dao.NHibernate;
namespace Vns.Erp.Core.Admin.Dao.NHibernate
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>
	[Serializable]
    public sealed class AppDvGroupDao : GenericDao<AppDvGroup, decimal>, IAppDvGroupDao
	{
        public void DeleteByG(Guid groupid)
        {
            String sql = "delete from AppDvGroup a where a.GroupId=:GroupId";
            IQuery q = NHibernateSession.CreateQuery(sql);
            q.SetParameter("GroupId", groupid);
            q.ExecuteUpdate();
        }
	}
}
