/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
using Vns.Erp.Core.Dao.NHibernate;
using Vns.Erp.Core.Asset.Domain;
using Vns.Erp.Core.Asset.Dao;
using Vns.Erp.Core.Dao;
using Spring.Transaction.Interceptor;
namespace Vns.Erp.Core.Asset.Dao.NHibernate
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>
    [Serializable]
    public sealed class DmNguonTscdDao : GenericDao<DmNguonTscd, Guid>, IDmNguonTscdDao
    {
        #region IDao
        DmNguonTscd IDao<DmNguonTscd, Guid>.Merge(DmNguonTscd entity)
        {
            if (VnsCheck.IsNullGuid(entity.Id)) entity.Id = Guid.NewGuid();
            HibernateTemplate.Merge(entity);

            return entity;
        }

        DmNguonTscd IDao<DmNguonTscd, Guid>.Save(DmNguonTscd entity)
        {
            if (VnsCheck.IsNullGuid(entity.Id)) entity.Id = Guid.NewGuid();
            HibernateTemplate.Save(entity);

            return entity;
        }

        DmNguonTscd IDao<DmNguonTscd, Guid>.SaveOrUpdate(DmNguonTscd entity)
        {
            if (VnsCheck.IsNullGuid(entity.Id)) entity.Id = Guid.NewGuid();
            HibernateTemplate.SaveOrUpdate(entity);

            return entity;
        }
        #endregion

        public IList<DmNguonTscd> GetByMaNguon(string MaDmNguonTscd, Guid DonviId)
        {
            string sql = "from DmNguonTscd a where a.MaDmNguonTscd like (:MaDmNguonTscd) and a.DonviId =(:DonviId)";
            IQuery q = NHibernateSession.CreateQuery(sql);
            q.SetParameter("MaDmNguonTscd", MaDmNguonTscd);
            q.SetParameter("DonviId", DonviId);
            return q.List<DmNguonTscd>();
        }
        public IList<DmNguonTscd> GetAllByDonviID(Guid DonviId)
        {
            string sql = "from DmNguonTscd a where a.DonviId =(:DonviId)";
            IQuery q = NHibernateSession.CreateQuery(sql);
            q.SetParameter("DonviId", DonviId);
            return q.List<DmNguonTscd>();
        }

    }
}
