/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Admin.Dao;
using Vns.Erp.Core.Admin.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
using System.ServiceModel.Activation;
namespace Vns.Erp.Core.Admin.Service
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
	public class DmVuviecService:GenericService<DmVuviec,Guid>, IDmVuviecService
	{
	     public IDmVuviecDao DmVuviecDao
        {
            get { return (IDmVuviecDao)Dao; }
            set { Dao = value; }
        }
         public int GetNumberVuViecByMaVuViec(string MaVuviec, Guid DonviId)
         {
             return DmVuviecDao.GetNumberVuViecByMaVuViec(MaVuviec, DonviId);
         }
         public IList<DmVuviec> GetAllByDonviID(Guid DonviId)
         {
             return DmVuviecDao.GetAllByDonviID(DonviId);
         }
	}
}
