/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using Nullables;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
using Vns.Erp.Core.Dao.NHibernate;
using Vns.Erp.Core.Admin.Domain;
using Vns.Erp.Core.Admin.Dao;
using Vns.Erp.Core.Dao;
using Spring.Transaction.Interceptor;
namespace Vns.Erp.Core.Admin.Dao.NHibernate
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>
	[Serializable]
	public sealed class DmThueDao:GenericDao<DmThue,Guid>,IDmThueDao
	{
        public int GetNumberDmThueByMaThue(String MaThue)
        {
            string sql = "select count(*) from DmThue a where (a.MaThue like :MaThue)";
            IQuery q = NHibernateSession.CreateQuery(sql);
            q.SetParameter("MaThue", MaThue);            
            long ret = q.UniqueResult<long>();
            return ((int)ret);
        }

        public IList<DmThue> GetDmThueByabc(Decimal XuatKhau, Decimal MuaHang)
        {
            //string sql = "select * from DmThue a a.XuatKhau = :XuatKhau and a.MuaHang = :MuaHang";
            //IQuery q = NHibernateSession.CreateQuery(sql);
            //q.SetParameter("XuatKhau", XuatKhau);
            //q.SetParameter("MuaHang", MuaHang);

            //return q.List<DmThue>();

            ArrayList props = new ArrayList();
            ArrayList values = new ArrayList();
            props.Add("XuatKhau");
            values.Add(XuatKhau);
            props.Add("MuaHang");
            values.Add(MuaHang);
            return List(-1, -1, props, values, null);
        }

	}
}
