/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
namespace Vns.Erp.Core.Accounting.Domain
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
    /// </summary>
    [Serializable]
    [DataContract(Namespace = "http://Vns.Erp.Core.Accounting", IsReference = true)]
    public partial class KtCtDHddv : DomainObject<Guid>, INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
        #region Private Members
        private bool _isChanged;
        private bool _isDeleted;
        private Guid _ctd_hddv_id;
        private Guid _cth_hddv_id;
        private Guid _tk_no_id;
        private string _ma_tk_no;
        private string _ten_tk_no;
        private Guid _tk_co_id;
        private string _ma_tk_co;
        private string _ten_tk_co;
        private decimal _so_tien;
        private decimal _so_tien_nte;
        private decimal _ty_le_ck;
        private decimal _so_tien_ck;
        private Guid _tk_no_id_ck;
        private string _ma_tk_no_ck;
        private Guid _tk_co_id_ck;
        private string _ma_tk_co_ck;
        private decimal _ty_le_thue_gtgt;
        private decimal _so_tien_thue_gtgt;
        private Guid _tk_no_id_gtgt;
        private string _ma_tk_no_gtgt;
        private Guid _tk_co_id_gtgt;
        private string _ma_tk_co_gtgt;
        private string _dvt;
        private decimal _so_luong;
        private decimal _don_gia;
        private string _noi_dung;
        private Guid _id_dm_hopdong_no;
        private string _ma_hopdong_no;
        private string _ky_hieu_hopdong_no;
        private string _ten_hopdong_no;
        private Guid _id_dm_hopdong_co;
        private string _ma_hopdong_co;
        private string _ky_hieu_hopdong_co;
        private string _ten_hopdong_co;
        private Guid _id_dm_ptqt_no;
        private Guid _id_dm_ptqt_co;
        private Guid _id_dm_phongban_no;
        private Guid _id_dm_phongban_co;
        private Guid _id_ct_ghiso;
        private string _ma_ct_ghiso_so;
        private string _ct_ghiso_trichyeu;
        private DateTime _ct_ghiso_ngay = Null.MIN_DATE;
        private decimal _da_ghiso;
        private Guid _id_dm_vuviec_no;
        private string _ma_vuviec_no;
        private string _ky_hieu_vuviec_no;
        private Guid _id_dm_vuviec_co;
        private string _ma_vuviec_co;
        private string _ky_hieu_vuviec_co;
        private Guid _id_dm_tudo_1_no;
        private Guid _id_dm_tudo_1_co;
        private Guid _id_dm_tudo_2_no;
        private Guid _id_dm_tudo_2_co;
        private Guid _id_dm_tudo_3_no;
        private Guid _id_dm_tudo_3_co;
        private Guid _id_dm_tudo_4_no;
        private Guid _id_dm_tudo_4_co;
        private Guid _id_dm_tudo_5_no;
        private Guid _id_dm_tudo_5_co;
        private decimal _loai_nghiep_vu;
        private Guid _id_khang_no;
        private string _ma_khang_no;
        private Guid _id_khang_co;
        private string _ma_khang_co;
        private Guid _id_doituong_1;
        private string _ma_doituong_1;
        private string _ten_doituong_1;
        private Guid _id_doituong_2;
        private string _ma_doituong_2;
        private string _ten_doituong_2;
        private Guid _id_doituong_3;
        private string _ma_doituong_3;
        private string _ten_doituong_3;
        private Guid _id_dm_khoanphi_no;
        private Guid _id_dm_khoanphi_co;
        private decimal _ty_gia_chenhlech;
        private decimal _nhom;
        private DateTime _bx_ngay_1 = Null.MIN_DATE;
        private DateTime _bx_ngay_2 = Null.MIN_DATE;
        private DateTime _bx_ngay_3 = Null.MIN_DATE;
        private decimal _bx_so_tien_1;
        private decimal _bx_so_tien_2;
        private decimal _bx_so_tien_3;
        private string _bx_dien_giai_1;
        private string _bx_dien_giai_2;
        private string _bx_dien_giai_3;
        private decimal _doanh_thu;
        private decimal _doanh_thu_nte;
        private decimal _tien_mg;
        private string _ten_hh_dv;
        private decimal _don_gia_nte;
        private decimal _so_tien_ck_nte;
        private Guid _id_doituong_hoadon;
        private decimal _phan_he;
        private string _ma_ro;
        private string _ten_ro;
        private string _ky_hieu_khang_no;
        private string _ten_khang_no;
        private string _ky_hieu_khang_co;
        private string _ten_khang_co;
        private Guid _thue_id;
        private string _ten_thue;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public KtCtDHddv()
        {
            _ctd_hddv_id = new Guid();
            _cth_hddv_id = new Guid();
            _tk_no_id = new Guid();
            _ma_tk_no = String.Empty;
            _ten_tk_no = String.Empty;
            _tk_co_id = new Guid();
            _ma_tk_co = String.Empty;
            _ten_tk_co = String.Empty;
            _so_tien = 0;
            _so_tien_nte = 0;
            _ty_le_ck = 0;
            _so_tien_ck = 0;
            _tk_no_id_ck = new Guid();
            _ma_tk_no_ck = String.Empty;
            _tk_co_id_ck = new Guid();
            _ma_tk_co_ck = String.Empty;
            _ty_le_thue_gtgt = 0;
            _so_tien_thue_gtgt = 0;
            _tk_no_id_gtgt = new Guid();
            _ma_tk_no_gtgt = String.Empty;
            _tk_co_id_gtgt = new Guid();
            _ma_tk_co_gtgt = String.Empty;
            _dvt = String.Empty;
            _so_luong = 0;
            _don_gia = 0;
            _noi_dung = String.Empty;
            _id_dm_hopdong_no = new Guid();
            _ma_hopdong_no = String.Empty;
            _ky_hieu_hopdong_no = String.Empty;
            _ten_hopdong_no = String.Empty;
            _id_dm_hopdong_co = new Guid();
            _ma_hopdong_co = String.Empty;
            _ky_hieu_hopdong_co = String.Empty;
            _ten_hopdong_co = String.Empty;
            _id_dm_ptqt_no = new Guid();
            _id_dm_ptqt_co = new Guid();
            _id_dm_phongban_no = new Guid();
            _id_dm_phongban_co = new Guid();
            _id_ct_ghiso = new Guid();
            _ma_ct_ghiso_so = String.Empty;
            _ct_ghiso_trichyeu = String.Empty;
            _ct_ghiso_ngay = DateTime.MaxValue;
            _da_ghiso = 0;
            _id_dm_vuviec_no = new Guid();
            _ma_vuviec_no = String.Empty;
            _ky_hieu_vuviec_no = String.Empty;
            _id_dm_vuviec_co = new Guid();
            _ma_vuviec_co = String.Empty;
            _ky_hieu_vuviec_co = String.Empty;
            _id_dm_tudo_1_no = new Guid();
            _id_dm_tudo_1_co = new Guid();
            _id_dm_tudo_2_no = new Guid();
            _id_dm_tudo_2_co = new Guid();
            _id_dm_tudo_3_no = new Guid();
            _id_dm_tudo_3_co = new Guid();
            _id_dm_tudo_4_no = new Guid();
            _id_dm_tudo_4_co = new Guid();
            _id_dm_tudo_5_no = new Guid();
            _id_dm_tudo_5_co = new Guid();
            _loai_nghiep_vu = 0;
            _id_khang_no = new Guid();
            _ma_khang_no = String.Empty;
            _id_khang_co = new Guid();
            _ma_khang_co = String.Empty;
            _id_doituong_1 = new Guid();
            _ma_doituong_1 = String.Empty;
            _ten_doituong_1 = String.Empty;
            _id_doituong_2 = new Guid();
            _ma_doituong_2 = String.Empty;
            _ten_doituong_2 = String.Empty;
            _id_doituong_3 = new Guid();
            _ma_doituong_3 = String.Empty;
            _ten_doituong_3 = String.Empty;
            _id_dm_khoanphi_no = new Guid();
            _id_dm_khoanphi_co = new Guid();
            _ty_gia_chenhlech = 0;
            _nhom = 0;
            _bx_ngay_1 = DateTime.MaxValue;
            _bx_ngay_2 = DateTime.MaxValue;
            _bx_ngay_3 = DateTime.MaxValue;
            _bx_so_tien_1 = 0;
            _bx_so_tien_2 = 0;
            _bx_so_tien_3 = 0;
            _bx_dien_giai_1 = String.Empty;
            _bx_dien_giai_2 = String.Empty;
            _bx_dien_giai_3 = String.Empty;
            _doanh_thu = 0;
            _doanh_thu_nte = 0;
            _tien_mg = 0;
            _ten_hh_dv = String.Empty;
            _don_gia_nte = 0;
            _so_tien_ck_nte = 0;
            _id_doituong_hoadon = new Guid();
            _phan_he = 0;
            _ma_ro = String.Empty;
            _ten_ro = String.Empty;
            _ky_hieu_khang_no = String.Empty;
            _ten_khang_no = String.Empty;
            _ky_hieu_khang_co = String.Empty;
            _ten_khang_co = String.Empty;
            _thue_id = new Guid();
            _ten_thue = String.Empty;
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid CtdHddvId
        {
            get { return _ctd_hddv_id; }
            set { _isChanged |= (_ctd_hddv_id != value); _ctd_hddv_id = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid CthHddvId
        {
            get { return _cth_hddv_id; }
            set { _isChanged |= (_cth_hddv_id != value); _cth_hddv_id = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid TkNoId
        {
            get { return _tk_no_id; }
            set { _isChanged |= (_tk_no_id != value); _tk_no_id = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaTkNo
        {
            get { return _ma_tk_no; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaTkNo", value, value.ToString());

                _isChanged |= (_ma_tk_no != value); _ma_tk_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenTkNo
        {
            get { return _ten_tk_no; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenTkNo", value, value.ToString());

                _isChanged |= (_ten_tk_no != value); _ten_tk_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid TkCoId
        {
            get { return _tk_co_id; }
            set { _isChanged |= (_tk_co_id != value); _tk_co_id = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaTkCo
        {
            get { return _ma_tk_co; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaTkCo", value, value.ToString());

                _isChanged |= (_ma_tk_co != value); _ma_tk_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenTkCo
        {
            get { return _ten_tk_co; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenTkCo", value, value.ToString());

                _isChanged |= (_ten_tk_co != value); _ten_tk_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoTien
        {
            get { return _so_tien; }
            set { _isChanged |= (_so_tien != value); _so_tien = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoTienNte
        {
            get { return _so_tien_nte; }
            set { _isChanged |= (_so_tien_nte != value); _so_tien_nte = Decimal.Round(value, 2); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal TyLeCk
        {
            get { return _ty_le_ck; }
            set { _isChanged |= (_ty_le_ck != value); _ty_le_ck = Decimal.Round(value, 2); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoTienCk
        {
            get { return _so_tien_ck; }
            set { _isChanged |= (_so_tien_ck != value); _so_tien_ck = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid TkNoIdCk
        {
            get { return _tk_no_id_ck; }
            set { _isChanged |= (_tk_no_id_ck != value); _tk_no_id_ck = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaTkNoCk
        {
            get { return _ma_tk_no_ck; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaTkNoCk", value, value.ToString());

                _isChanged |= (_ma_tk_no_ck != value); _ma_tk_no_ck = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid TkCoIdCk
        {
            get { return _tk_co_id_ck; }
            set { _isChanged |= (_tk_co_id_ck != value); _tk_co_id_ck = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaTkCoCk
        {
            get { return _ma_tk_co_ck; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaTkCoCk", value, value.ToString());

                _isChanged |= (_ma_tk_co_ck != value); _ma_tk_co_ck = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal TyLeThueGtgt
        {
            get { return _ty_le_thue_gtgt; }
            set { _isChanged |= (_ty_le_thue_gtgt != value); _ty_le_thue_gtgt = Decimal.Round(value, 2); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoTienThueGtgt
        {
            get { return _so_tien_thue_gtgt; }
            set { _isChanged |= (_so_tien_thue_gtgt != value); _so_tien_thue_gtgt = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid TkNoIdGtgt
        {
            get { return _tk_no_id_gtgt; }
            set { _isChanged |= (_tk_no_id_gtgt != value); _tk_no_id_gtgt = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaTkNoGtgt
        {
            get { return _ma_tk_no_gtgt; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaTkNoGtgt", value, value.ToString());

                _isChanged |= (_ma_tk_no_gtgt != value); _ma_tk_no_gtgt = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid TkCoIdGtgt
        {
            get { return _tk_co_id_gtgt; }
            set { _isChanged |= (_tk_co_id_gtgt != value); _tk_co_id_gtgt = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaTkCoGtgt
        {
            get { return _ma_tk_co_gtgt; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaTkCoGtgt", value, value.ToString());

                _isChanged |= (_ma_tk_co_gtgt != value); _ma_tk_co_gtgt = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string Dvt
        {
            get { return _dvt; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for Dvt", value, value.ToString());

                _isChanged |= (_dvt != value); _dvt = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoLuong
        {
            get { return _so_luong; }
            set { _isChanged |= (_so_luong != value); _so_luong = Decimal.Round(value, 2); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal DonGia
        {
            get { return _don_gia; }
            set { _isChanged |= (_don_gia != value); _don_gia = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string NoiDung
        {
            get { return _noi_dung; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for NoiDung", value, value.ToString());

                _isChanged |= (_noi_dung != value); _noi_dung = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmHopdongNo
        {
            get { return _id_dm_hopdong_no; }
            set { _isChanged |= (_id_dm_hopdong_no != value); _id_dm_hopdong_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaHopdongNo
        {
            get { return _ma_hopdong_no; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaHopdongNo", value, value.ToString());

                _isChanged |= (_ma_hopdong_no != value); _ma_hopdong_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuHopdongNo
        {
            get { return _ky_hieu_hopdong_no; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuHopdongNo", value, value.ToString());

                _isChanged |= (_ky_hieu_hopdong_no != value); _ky_hieu_hopdong_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenHopdongNo
        {
            get { return _ten_hopdong_no; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenHopdongNo", value, value.ToString());

                _isChanged |= (_ten_hopdong_no != value); _ten_hopdong_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmHopdongCo
        {
            get { return _id_dm_hopdong_co; }
            set { _isChanged |= (_id_dm_hopdong_co != value); _id_dm_hopdong_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaHopdongCo
        {
            get { return _ma_hopdong_co; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaHopdongCo", value, value.ToString());

                _isChanged |= (_ma_hopdong_co != value); _ma_hopdong_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuHopdongCo
        {
            get { return _ky_hieu_hopdong_co; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuHopdongCo", value, value.ToString());

                _isChanged |= (_ky_hieu_hopdong_co != value); _ky_hieu_hopdong_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenHopdongCo
        {
            get { return _ten_hopdong_co; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenHopdongCo", value, value.ToString());

                _isChanged |= (_ten_hopdong_co != value); _ten_hopdong_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmPtqtNo
        {
            get { return _id_dm_ptqt_no; }
            set { _isChanged |= (_id_dm_ptqt_no != value); _id_dm_ptqt_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmPtqtCo
        {
            get { return _id_dm_ptqt_co; }
            set { _isChanged |= (_id_dm_ptqt_co != value); _id_dm_ptqt_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmPhongbanNo
        {
            get { return _id_dm_phongban_no; }
            set { _isChanged |= (_id_dm_phongban_no != value); _id_dm_phongban_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmPhongbanCo
        {
            get { return _id_dm_phongban_co; }
            set { _isChanged |= (_id_dm_phongban_co != value); _id_dm_phongban_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdCtGhiso
        {
            get { return _id_ct_ghiso; }
            set { _isChanged |= (_id_ct_ghiso != value); _id_ct_ghiso = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaCtGhisoSo
        {
            get { return _ma_ct_ghiso_so; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaCtGhisoSo", value, value.ToString());

                _isChanged |= (_ma_ct_ghiso_so != value); _ma_ct_ghiso_so = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string CtGhisoTrichyeu
        {
            get { return _ct_ghiso_trichyeu; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for CtGhisoTrichyeu", value, value.ToString());

                _isChanged |= (_ct_ghiso_trichyeu != value); _ct_ghiso_trichyeu = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public DateTime CtGhisoNgay
        {
            get { return _ct_ghiso_ngay; }
            set { _isChanged |= (_ct_ghiso_ngay != value); _ct_ghiso_ngay = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal DaGhiso
        {
            get { return _da_ghiso; }
            set { _isChanged |= (_da_ghiso != value); _da_ghiso = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmVuviecNo
        {
            get { return _id_dm_vuviec_no; }
            set { _isChanged |= (_id_dm_vuviec_no != value); _id_dm_vuviec_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaVuviecNo
        {
            get { return _ma_vuviec_no; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaVuviecNo", value, value.ToString());

                _isChanged |= (_ma_vuviec_no != value); _ma_vuviec_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuVuviecNo
        {
            get { return _ky_hieu_vuviec_no; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuVuviecNo", value, value.ToString());

                _isChanged |= (_ky_hieu_vuviec_no != value); _ky_hieu_vuviec_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmVuviecCo
        {
            get { return _id_dm_vuviec_co; }
            set { _isChanged |= (_id_dm_vuviec_co != value); _id_dm_vuviec_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaVuviecCo
        {
            get { return _ma_vuviec_co; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaVuviecCo", value, value.ToString());

                _isChanged |= (_ma_vuviec_co != value); _ma_vuviec_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuVuviecCo
        {
            get { return _ky_hieu_vuviec_co; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuVuviecCo", value, value.ToString());

                _isChanged |= (_ky_hieu_vuviec_co != value); _ky_hieu_vuviec_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo1No
        {
            get { return _id_dm_tudo_1_no; }
            set { _isChanged |= (_id_dm_tudo_1_no != value); _id_dm_tudo_1_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo1Co
        {
            get { return _id_dm_tudo_1_co; }
            set { _isChanged |= (_id_dm_tudo_1_co != value); _id_dm_tudo_1_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo2No
        {
            get { return _id_dm_tudo_2_no; }
            set { _isChanged |= (_id_dm_tudo_2_no != value); _id_dm_tudo_2_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo2Co
        {
            get { return _id_dm_tudo_2_co; }
            set { _isChanged |= (_id_dm_tudo_2_co != value); _id_dm_tudo_2_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo3No
        {
            get { return _id_dm_tudo_3_no; }
            set { _isChanged |= (_id_dm_tudo_3_no != value); _id_dm_tudo_3_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo3Co
        {
            get { return _id_dm_tudo_3_co; }
            set { _isChanged |= (_id_dm_tudo_3_co != value); _id_dm_tudo_3_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo4No
        {
            get { return _id_dm_tudo_4_no; }
            set { _isChanged |= (_id_dm_tudo_4_no != value); _id_dm_tudo_4_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo4Co
        {
            get { return _id_dm_tudo_4_co; }
            set { _isChanged |= (_id_dm_tudo_4_co != value); _id_dm_tudo_4_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo5No
        {
            get { return _id_dm_tudo_5_no; }
            set { _isChanged |= (_id_dm_tudo_5_no != value); _id_dm_tudo_5_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmTudo5Co
        {
            get { return _id_dm_tudo_5_co; }
            set { _isChanged |= (_id_dm_tudo_5_co != value); _id_dm_tudo_5_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal LoaiNghiepVu
        {
            get { return _loai_nghiep_vu; }
            set { _isChanged |= (_loai_nghiep_vu != value); _loai_nghiep_vu = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdKhangNo
        {
            get { return _id_khang_no; }
            set { _isChanged |= (_id_khang_no != value); _id_khang_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaKhangNo
        {
            get { return _ma_khang_no; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaKhangNo", value, value.ToString());

                _isChanged |= (_ma_khang_no != value); _ma_khang_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdKhangCo
        {
            get { return _id_khang_co; }
            set { _isChanged |= (_id_khang_co != value); _id_khang_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaKhangCo
        {
            get { return _ma_khang_co; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaKhangCo", value, value.ToString());

                _isChanged |= (_ma_khang_co != value); _ma_khang_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDoituong1
        {
            get { return _id_doituong_1; }
            set { _isChanged |= (_id_doituong_1 != value); _id_doituong_1 = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaDoituong1
        {
            get { return _ma_doituong_1; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for MaDoituong1", value, value.ToString());

                _isChanged |= (_ma_doituong_1 != value); _ma_doituong_1 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenDoituong1
        {
            get { return _ten_doituong_1; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenDoituong1", value, value.ToString());

                _isChanged |= (_ten_doituong_1 != value); _ten_doituong_1 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDoituong2
        {
            get { return _id_doituong_2; }
            set { _isChanged |= (_id_doituong_2 != value); _id_doituong_2 = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaDoituong2
        {
            get { return _ma_doituong_2; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for MaDoituong2", value, value.ToString());

                _isChanged |= (_ma_doituong_2 != value); _ma_doituong_2 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenDoituong2
        {
            get { return _ten_doituong_2; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenDoituong2", value, value.ToString());

                _isChanged |= (_ten_doituong_2 != value); _ten_doituong_2 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDoituong3
        {
            get { return _id_doituong_3; }
            set { _isChanged |= (_id_doituong_3 != value); _id_doituong_3 = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaDoituong3
        {
            get { return _ma_doituong_3; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for MaDoituong3", value, value.ToString());

                _isChanged |= (_ma_doituong_3 != value); _ma_doituong_3 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenDoituong3
        {
            get { return _ten_doituong_3; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenDoituong3", value, value.ToString());

                _isChanged |= (_ten_doituong_3 != value); _ten_doituong_3 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmKhoanphiNo
        {
            get { return _id_dm_khoanphi_no; }
            set { _isChanged |= (_id_dm_khoanphi_no != value); _id_dm_khoanphi_no = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDmKhoanphiCo
        {
            get { return _id_dm_khoanphi_co; }
            set { _isChanged |= (_id_dm_khoanphi_co != value); _id_dm_khoanphi_co = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal TyGiaChenhlech
        {
            get { return _ty_gia_chenhlech; }
            set { _isChanged |= (_ty_gia_chenhlech != value); _ty_gia_chenhlech = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal Nhom
        {
            get { return _nhom; }
            set { _isChanged |= (_nhom != value); _nhom = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public DateTime BxNgay1
        {
            get { return _bx_ngay_1; }
            set { _isChanged |= (_bx_ngay_1 != value); _bx_ngay_1 = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public DateTime BxNgay2
        {
            get { return _bx_ngay_2; }
            set { _isChanged |= (_bx_ngay_2 != value); _bx_ngay_2 = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public DateTime BxNgay3
        {
            get { return _bx_ngay_3; }
            set { _isChanged |= (_bx_ngay_3 != value); _bx_ngay_3 = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal BxSoTien1
        {
            get { return _bx_so_tien_1; }
            set { _isChanged |= (_bx_so_tien_1 != value); _bx_so_tien_1 = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal BxSoTien2
        {
            get { return _bx_so_tien_2; }
            set { _isChanged |= (_bx_so_tien_2 != value); _bx_so_tien_2 = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal BxSoTien3
        {
            get { return _bx_so_tien_3; }
            set { _isChanged |= (_bx_so_tien_3 != value); _bx_so_tien_3 = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string BxDienGiai1
        {
            get { return _bx_dien_giai_1; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for BxDienGiai1", value, value.ToString());

                _isChanged |= (_bx_dien_giai_1 != value); _bx_dien_giai_1 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string BxDienGiai2
        {
            get { return _bx_dien_giai_2; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for BxDienGiai2", value, value.ToString());

                _isChanged |= (_bx_dien_giai_2 != value); _bx_dien_giai_2 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string BxDienGiai3
        {
            get { return _bx_dien_giai_3; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for BxDienGiai3", value, value.ToString());

                _isChanged |= (_bx_dien_giai_3 != value); _bx_dien_giai_3 = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal DoanhThu
        {
            get { return _doanh_thu; }
            set { _isChanged |= (_doanh_thu != value); _doanh_thu = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal DoanhThuNte
        {
            get { return _doanh_thu_nte; }
            set { _isChanged |= (_doanh_thu_nte != value); _doanh_thu_nte = Decimal.Round(value, 2); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal TienMg
        {
            get { return _tien_mg; }
            set { _isChanged |= (_tien_mg != value); _tien_mg = Decimal.Round(value, 0); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenHhDv
        {
            get { return _ten_hh_dv; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for TenHhDv", value, value.ToString());

                _isChanged |= (_ten_hh_dv != value); _ten_hh_dv = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal DonGiaNte
        {
            get { return _don_gia_nte; }
            set { _isChanged |= (_don_gia_nte != value); _don_gia_nte = Decimal.Round(value, 2); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoTienCkNte
        {
            get { return _so_tien_ck_nte; }
            set { _isChanged |= (_so_tien_ck_nte != value); _so_tien_ck_nte = Decimal.Round(value, 2); }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid IdDoituongHoadon
        {
            get { return _id_doituong_hoadon; }
            set { _isChanged |= (_id_doituong_hoadon != value); _id_doituong_hoadon = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal PhanHe
        {
            get { return _phan_he; }
            set { _isChanged |= (_phan_he != value); _phan_he = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string MaRo
        {
            get { return _ma_ro; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaRo", value, value.ToString());

                _isChanged |= (_ma_ro != value); _ma_ro = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenRo
        {
            get { return _ten_ro; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenRo", value, value.ToString());

                _isChanged |= (_ten_ro != value); _ten_ro = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuKhangNo
        {
            get { return _ky_hieu_khang_no; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuKhangNo", value, value.ToString());

                _isChanged |= (_ky_hieu_khang_no != value); _ky_hieu_khang_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenKhangNo
        {
            get { return _ten_khang_no; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for TenKhangNo", value, value.ToString());

                _isChanged |= (_ten_khang_no != value); _ten_khang_no = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string KyHieuKhangCo
        {
            get { return _ky_hieu_khang_co; }
            set
            {
                if (value != null)
                    if (value.Length > 64)
                        throw new ArgumentOutOfRangeException("Invalid value for KyHieuKhangCo", value, value.ToString());

                _isChanged |= (_ky_hieu_khang_co != value); _ky_hieu_khang_co = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public string TenKhangCo
        {
            get { return _ten_khang_co; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for TenKhangCo", value, value.ToString());

                _isChanged |= (_ten_khang_co != value); _ten_khang_co = value;
            }
        }


        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return _isChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsDeleted
        {
            get { return _isDeleted; }
        }

        [DataMember]
        public Guid ThueId
        {
            get { return _thue_id; }
            set
            {
                _isChanged |= (_thue_id != value); _thue_id = value;
            }
        }

        [DataMember]
        public string TenThue
        {
            get { return _ten_thue; }
            set
            {
                if (value != null)
                    if (value.Length > 256)
                        throw new ArgumentOutOfRangeException("Invalid value for NoiDung", value, value.ToString());

                _isChanged |= (_ten_thue != value); _ten_thue = value;
            }
        }
        #endregion

        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public void MarkAsDeleted()
        {
            _isDeleted = true;
            _isChanged = true;
        }


        #endregion

        #region Equals And HashCode Overrides
        /// <summary>
        /// local implementation of Equals based on unique value members
        /// </summary>
        public override bool Equals(object obj)
        {
            if (this == obj) return true;
            if ((obj == null) || (obj.GetType() != this.GetType())) return false;
            KtCtDHddv castObj = (KtCtDHddv)obj;
            return (castObj != null) &&
                (this._ctd_hddv_id == castObj.CtdHddvId);
        }

        /// <summary>
        /// local implementation of GetHashCode based on unique value members
        /// </summary>
        public override int GetHashCode()
        {

            int hash = 57;
            hash = 27 * hash * _ctd_hddv_id.GetHashCode();
            return hash;
        }
        #endregion

    }
}
